cstorm2/urls.py
from django.conf.urls import include,url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^comp/', include('round2.urls')),
]

round2/urls.py
from django.conf.urls import url
from . import views

app_name = 'round2'

urlpatterns = [
    # /round2/question/(user_id)
    url(r'^question/(?P<user_id>[0-9]+)/$', views.question, name="question"),
    url(r'^add_que/(?P<user_id>[0-9]+)/$', views.add_que, name="add_que"),
    #/round2/login)
    url(r'^register/$', views.register, name="register"),
    #/round2/login/create_user
    url(r'^login/create_user1/$', views.create_user1, name="create_user1"),
    # /round2/user_id/(question_id)
    url(r'^(?P<user_id>[0-9]+)/(?P<question_id>[0-9]+)/$', views.question_details, name='question_details'),
    # /round2/question/(user_id)/(question_id)
    url(r'^(?P<user_id>[0-9]+)/(?P<question_id>[0-9]+)/next/$', views.handle_answer, name='handle_answer'),
    #url(r'^buy_question/(?P<user_id>[0-9]+)/(?P<question_id>[0-9]+)/$', views.buy_question, name='buy_question'),
    url(r'^leaderboard/(?P<user_id>[0-9]+)/$', views.leaderboard, name='leaderboard'),
    url(r'^instruction_view/(?P<user_id>[0-9]+)/(?P<question_id>[0-9]+)/$', views.instruction_view, name='instruction_view'),
    url(r'^(?P<user_id>[0-9]+)/(?P<question_id>[0-9]+)/$', views.save_answer, name='save_answer'),

]

round2/models.py
from django.db import models


class User(models.Model):
    login_name = models.CharField(max_length=100)
    phone_number1 = models.IntegerField(default=0)
    phone_number2 = models.IntegerField(default=0)
    college_name1 = models.CharField(max_length=100)
    college_name2 = models.CharField(max_length=100, default = '')
    user_name1 = models.CharField(max_length=100)
    user_name2 = models.CharField(max_length=100, default = '')
    email1 = models.CharField(max_length=100)
    email2 = models.CharField(max_length=100, default = '')
    total_score = models.IntegerField(default=0)
    end_time = models.IntegerField(default=0)
    #score = models.TextField()
    money = models.IntegerField(default=0)
    easy_counter = models.IntegerField(default=0)
    cnt = models.IntegerField(default = 1)

    def __str__(self):
        return str(self.pk)


class Question(models.Model):
    question = models.TextField(max_length=4000)
    question_title = models.CharField(max_length=2000)
    input = models.CharField(default=0, max_length=15000)
    correct_op = models.CharField(default=0, max_length=10000)
    explanation = models.TextField(max_length=7000)
    test_input = models.TextField(max_length=100000)

    test_output = models.TextField(max_length=10000)
    cost = models.IntegerField(default = 100)
    user = models.ManyToManyField(User, null=True, through="Score")
    type = models.CharField(default="Easy", max_length=10)

    def __str__(self):
        return self.question_title


class Score(models.Model):
    user_f = models.ForeignKey(User, on_delete=models.CASCADE)
    question_f = models.ForeignKey(Question, on_delete=models.CASCADE)
    score = models.IntegerField(default=0)
    language_preferred = models.CharField(default='c', max_length=500)

round2/views.py
import os
import signal

from django.shortcuts import render, HttpResponse
from .models import User, Question, Score
import subprocess
from subprocess import Popen, PIPE, STDOUT
import json
import random, math
# import pyperclip
# from subprocess import Popen, PIPE
import time
import threading

import signal, sys

time_finish = True
ps_id = 0
tle = False
question_list = []


# Working code
tle_array = [False for i in range(20)]


def check_tle(pid, i):
    time.sleep(1)
    #     global tle
    try:
        os.killpg(os.getpgid(pid), signal.SIGTERM)
        tle_array[i] = True
    except:
        tle_array[i] = False

# Ends here

def timeout(sig, frm):
    print('timeout')
    # time_finish = True
    if time_finish == True:
        print("Finished")
        os.killpg(os.getpgid(ps_id), signal.SIGTERM)
        tle = True
        return HttpResponse("TLE")
        # raise Exception

    signal.signal(signal.SIGALRM, timeout)


def question(request, user_id):
    all_questions = Question.objects.all()
    current_user = User.objects.get(pk=user_id)
    jsonDec = json.decoder.JSONDecoder()
    # all_marks = list(jsonDec.decode(current_user. score))
    current_user.total_score = 0
    temp = 0
    # for marks in all_marks:
    #     temp += marks
    question_list = []
    for questions in all_questions:
        if current_user in questions.user.all():
            question_list.append({"question": questions,
                                  "status": "bought",
                                  "cost": questions.cost,
                                  "difficulty": questions.type,
                                  "question_score": Score.objects.get(user_f=current_user, question_f=questions).score})

    current_user.total_score = temp
    if current_user.cnt <= 2:
    	current_user.end_time=(time.time() + (60 * 15))
    elif current_user.cnt > 2 and current_user.cnt <= 3:
    	current_user.end_time = (time.time() + (60 * 10))
    current_user.save()
    print(current_user.total_score)
    # return render(request, 'round2/questions_list.html', {'all_questions' : all_questions, 'user_id': user_id,'remaining_time':current_user.end_time-time.time(),'all_marks':all_marks ,'one':50,'two':50,'three':100,'four':100})
    return render(request, 'round2/select_questions_new.html',
                  {'buyed_questions': '', 'all_questions': all_questions, 'user_id': user_id,
                   'remaining_time': current_user.end_time - time.time(), 'question_list': question_list,
                   'money': current_user.money})


def register(request):
    return render(request, 'round2/register_new.html', {})


def create_user1(request):
    team_name = request.POST.get('team_name')
    participant1 = request.POST.get('participant1')
    participant2 = request.POST.get('participant2')
    mobile1 = request.POST.get('mobile1')
    college1 = request.POST.get('college1')
    email1 = request.POST.get('email1')
    reciept_number = request.POST.get('reciept_number')
    msg = ''
    
    question_list = Question.objects.all()
    new_user = User(login_name=team_name, phone_number1=mobile1,
                    college_name1=college1, user_name1=participant1, user_name2=participant2, email1=email1,
                    end_time=(time.time() + (60 * 10)), cnt = 1)
    new_user.cnt = 1
    print(new_user.end_time)
    new_user.save()
                    
    random_index = math.floor(random.random()*len(question_list))
    question = question_list[random_index]
    score_ob = Score(user_f = new_user , question_f = question)
    score_ob.save()
    # return question(request,new_user.pk)
    return instruction_view(request, new_user.pk, question.pk)
    

def question_details(request, user_id, question_id):
    selected_question = Question.objects.get(pk=question_id)
    # print(selected_question)
    current_user = User.objects.get(pk=user_id)
    if current_user.cnt <= 3:
        current_user.end_time = (time.time() + (60 * 15))
    elif current_user.cnt > 3 and current_user.cnt <= 6:
        current_user.end_time = (time.time() + (60 * 10))
    current_user.save()
    try:
        score_object = Score.objects.get(user_f=current_user, question_f=selected_question)
        language = score_object.language_preferred
    except:
        language = 'c'

    file_extension = 'c'

    if language == 'cpp':
        file_extension = 'cpp'
    elif language == 'cpp14':
        file_extension = 'cpp'

    # print(current_user.end_time)
    # print(current_user.end_time - time.time())

    input_file = str(question_id) + '_' + str(user_id)
    bought = False
    if current_user in selected_question.user.all():
        bought = True

    jsonDec = json.decoder.JSONDecoder()
    # current_user.total_score = 0
    # all_marks = list(jsonDec.decode(current_user.score))
    # for marks in all_marks:
    #     current_user.total_score += marks
    current_user.save()
    if os.path.isfile(input_file + '.' + file_extension):
        f = open(input_file + '.' + file_extension, 'r')
        f.flush()
        previous_code = f.read()
        f.close()
    else:
        previous_code = ""

    return render(request, 'round2/question_details.html',
                  {'pegs_id': int("3"), 'bought': bought, 'selected_question': selected_question,
                   'question_id': selected_question.pk,
                   'user_id': user_id, 'submitted_code': previous_code,
                   'remaining_time': current_user.end_time - time.time(),
                   'money':0, 'language': language})


def handle_answer(request, user_id, question_id):
    if request.POST.get("finish"):
        return leaderboard(request, user_id)
    # code = request.POST.get("text_area")
    # print(language)
    input_file = str(question_id) + '_' + str(user_id)
    language = request.POST.get("language")

    file_extension = 'c'
    # changes more
    compiler = 'gcc '
    #print('This is the language selected ' + language)
    if language == 'cpp':
        compiler = 'g++ -std=c++11 '
        file_extension = 'cpp'

    elif language == 'cpp14':
        compiler = 'g++ -std=c++14 '
        file_extension = 'cpp'

    code = request.POST.get("text_area")
    f = open(input_file + '.' + file_extension, 'w')
    # f=open('test.cpp','w')
    f.write(code)
    f.close()

    current_user = User.objects.get(pk=user_id)
    current_question = Question.objects.get(pk=question_id)
    score_object = Score.objects.get(user_f=current_user, question_f=current_question)
    jsonDec = json.decoder.JSONDecoder()

    score_object.language_preferred = language
    score_object.save()


    compile_output = subprocess.getoutput(
        compiler + ' -o ' + input_file + ' ' + input_file + '.' + file_extension)

    if not compile_output:
        correct_op = jsonDec.decode(current_question.correct_op)

        input_value = jsonDec.decode(current_question.input)
        print('this is input values list')
        print(input_value)

        checker = [None] * len(correct_op)

        score = 0
        score_for_one = (current_question.cost) / len(correct_op)

        for tc in range(0, len(input_value)):
            print(tc)
            input_str = ""
            for i in input_value[tc]:
                input_str += (str(i) + '\n')

            print('giving this as input ' + input_str)

            process = Popen(['./' + input_file], shell=True, stdout=PIPE, stderr=PIPE, stdin=PIPE, preexec_fn=os.setsid)
            tle_array[tc] = False

            process.stdin.write(input_str.encode())
            process.stdin.flush()

            tle_thread = threading.Thread(target=check_tle, args=(process.pid, tc))
            tle_thread.start()

            errors = ""
            # errors = process.stderr.readline()

            output = process.communicate()[0].rstrip()

            if tle_array[tc]:
                print('Time Limit Exceed')
                checker[tc] = 2
            else:

                try:
                    output = output.decode()
                except:
                    pass

                print('This is the output of program')
                print(output)
                # generated_output = output.split()
                # print(generated_output)
                # score = 0
                # score_for_one = (current_question.cost * 2) / len(correct_op)
                print('This is the correct output')
                print(correct_op[tc])

                if(current_question.pk == 15):
                    output = float(output)
                    check = float(correct_op[tc])

                    if(check-output < 0.000001 or output-check < 0.000001):
                        score += score_for_one
                        checker[tc] = 1

                if (current_question.pk != 15 and str(output) == str(correct_op[tc])):
                    print("And this is correct")
                    score += score_for_one
                    checker[tc] = 1

            tle_array[tc] = False
        if score >= 75:
        	score += (current_user.end_time - time.time()) * 0.1
        if score > score_object.score:
            current_user.total_score += (score - score_object.score)
            current_user.save()
            score_object.score = score
            score_object.save()

        return render(request, 'round2/question_details.html',
                      {'pegs_id': int("3"), 'error_msg': False, 'submitted': True, 'one': 50, 'two': 50,
                       'three': 100, 'four': 100, 'submitted_code': code, 'selected_question': current_question,
                       'user_id': user_id, 'checker': checker, "one_score":score_for_one,
                       'remaining_time': current_user.end_time - time.time(), 'error_msg': errors,
                       'bought': True, 'question_id': question_id, 'question_score': score_object.score,
                       'money': current_user.money, 'language': score_object.language_preferred})


    else:

round2/templates/round2/leaderboard_new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>

    <link href="https://fonts.googleapis.com/css?family=Merriweather:900" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet"
          href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.min.css">
    <script src="http://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">


    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <style>
        .leader {
            background: whitesmoke;
        }
    </style>
</head>
<body>
<br>
<div class="container">
        <center>
            {% if leaderboard_clicked %}
                <form action="{% url 'round2:question' user_id %}">
                    <input class="btn btn-primary" type="submit" name="back" id="back" value="Back">

                </form>
            {% else %}
            	<script>
            		history.pushState(null, null, document.title);
			window.addEventListener('popstate', function () {
			    history.pushState(null, null, document.title);
			    alert('The only way is Ahead..!!!');
			});
		</script>
            {% endif %}

        </center>
    <div class="row">
        <div STYLE="text-align: center; font-weight: bolder" class="col-md-4 col-md-offset-4">
            <H3>LEADER BOARD</H3>
		<form action="{% url 'round2:register' %}">
			<input class="btn btn-primary" style="margin: auto; margin-bottom: 20px;" type="submit" name="home" id="home" value="Home">
		</form>
        </div>
    </div>
    <div class="row leader">
        <div class="table-responsive">
            <table class="table table-bordered white">
                <thead class="thead-inverse">
                <tr>
                    <th style="width:4%">RANK</th>
                    <th>USERNAME</th>
                    <th>COLLEGE</th>
                    <th>SCORE</th>
                </tr>
                </thead>
                <tbody id="table_body">
                {% for user in all_user %}

                    {% ifequal user_id user.pk %}

                        <tr bgcolor="#BBBBBB" style="color:#000000">

                            {% else %}
                        <tr>
                    {% endifequal %}
                <td>{{ forloop.counter }}</td>
                <td>{{ user.login_name }}</td>
                <td>{{ user.college_name1 }}</td>
                <td>{{ user.total_score }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

</div>
</body>
</html>

round2/templates/round2/questions_list.html
<style>
  div.fixed {
    position: fixed;
    margin-left:80%;
    margin-top:0%;

}
#code_editor1,#code_editor2,#code_editor3,#code_editor4,#code_editor5,#message_display{
	width: 75%;
	height:10%;
		border: 0.5px solid; border-color: #E4E4E4;
		background:#ffffff;
		  margin-left: 3%;  margin-bottom: 2%;
		padding: 1%;
		font-size:150%;
		font-family:Comic Sans MS;
	}
	body{
		background: #F3F3FF;
		          font-family: Arial, Helvetica, sans-serif;
	}

a:link {
    color: #0C090A;
    background-color: transparent;
    text-decoration: none;
}
a:visited {
    color: #33348e;
    background-color: transparent;
    text-decoration: none;
}
a:hover {
    color: #625D5D;
    background-color: transparent;
    text-decoration: underline;
}
a:active {
    color: #33348e;
    background-color: transparent;
    text-decoration: underline;
}



h1{
font-size:250%;

 font-family: "Comic Sans MS";

}
input[type="submit"],button{
/* change these properties to whatever you want */
 width="50";
 height="0.5";
 padding: 6px 17px;

  font-size: 15px;
  text-align: center;
  cursor: pointer;
background-color: #6D6968;
color: #fff;
border-radius: 4px;
}
input[type="submit"]:hover {background-color: #D1D0DE;
border-radius:7px;
color: #2C3539;

}
button:hover {background-color: #D1D0DE;
border-radius:7px;
color: #2C3539;

}
table,th,td{

border-collapse:collapse;
background-color:#ffffff;

 font-family:"Comic Sans MS";
}

</style>
<body >

    <h1 STYLE="margin-left:10%; ">Problem Statements </h1>
<div class="fixed">
    <label type="label" style= "background-color:black;color:#F3F3F3;font-family:courier;font-size:300%;margin-top:-15px;  " border="0"><b>
      <span id="time1"></span></b>

    </label>
</div>





<table style="margin-left:3%; width:75%; height:70%;">
    <tr  id="title" style=" font-weight: bold; font-size:145%;border:2px solid #E4E4E4;"><th>SOLVE PROBLEM</th> <th>YOUR SCORE</th><th> MAX SCORES </th></tr>
{% for question in all_questions %}

<tr id="{{forloop.counter}}" STYLE="border:1px solid #E4E4E4;"><td><a href="{% url 'round2:question_details' user_id question.pk  %}" style=" font-size: 150%; text-align:left; margin-left:10%;">{{question}}</a></td>
    {% for marks in all_marks %}
    {% ifequal forloop.parentloop.counter forloop.counter %}
    <td style="text-align:center;">{{marks}}</td><td style="text-align:center;">
    {% ifequal forloop.counter 1 %}
        {{one}}
     {% endifequal %}
     {% ifequal forloop.counter 2 %}
        {{two}}
     {% endifequal %}
     {% ifequal forloop.counter 3 %}
        {{three}}
     {% endifequal %}
        {% ifequal forloop.counter 4 %}
        {{four}}
     {% endifequal %}
        {% ifequal forloop.counter 5 %}
        {{five}}
     {% endifequal %}

    </td></tr>
    {% endifequal %}
    {% endfor %}
 {% endfor %}
</table>


<form action="{% url 'round2:leaderboard' user_id %}" method="post">
    {% csrf_token %}
    <input type="submit" name="leader" id="leader" value="View Leaderboard" style="margin-left:70%;margin-top:3%;">

</form>
    <button onclick="prompt_user()" style="margin-left:75%;" >Finish</button>

<script>
    function prompt_user(){
    if (confirm('Are you sure you want to save this thing into the database?')) {
    window.location.replace(" {%url 'round2:leaderboard' user_id %}" );
} else {
    // Do nothing!
}
    }
</script>

</body>
<script type="text/javascript">

          function startTimer(duration, display)
          {
        var start = Date.now(),

        diff,
        minutes,
        seconds;

        function timer() {
        // get the number of seconds that have elapsed since
        // startTimer() was called
        diff = duration - (((Date.now() - start) / 1000) | 0);

        // does the same job as parseInt truncates the float
        hours = (diff / 3600) | 0;
        minutes = ((diff/60)%60) | 0;
        seconds = (diff % 60) | 0;
        hours = hours < 10 ? "0" + hours : hours;
        minutes = minutes < 10 ? "0" + minutes : minutes;
        seconds = seconds < 10 ? "0" + seconds : seconds;

        display.textContent =hours+ ":" + minutes + ":" + seconds;


        if (diff <= 0) {
            // add one second so that the count down starts at the full duration
            // example 05:00 not 04:59
           // start = Date.now() + 1000;
          // window.location.replace("http:/comp/leaderboard/" );
           window.location.replace(" {%url 'round2:instruction_view' user_id %}");

        }

    };
    // we don't want to wait a full second before the timer starts
    timer();
    setInterval(timer, 1000);
}
window.onload = function ()
{
    var v = "{{remaining_time}}";

    display = document.querySelector('#time1');
    startTimer( v, display);
};

</script>


round2/templates/round2/select_questions.html
<!DOCTYPE html>
<html lang="en">
<style>

    body {
        background: #F3F3FF;
        font-family: Arial, Helvetica, sans-serif;
    }

    table, th, td {

        border-collapse: collapse;
        background-color: #ffffff;

        font-family: serif;
    }
</style>
<head>


</head>
<body>
<form action="{% url 'round2:leaderboard' user_id %}" method="post">
    {% csrf_token %}
    <input type="submit" name="leader" id="leader" value="View Leaderboard" style="margin-left:70%;margin-top:3%;">

</form>
    <button onclick="prompt_user()" style="margin-left:75%;" >Finish</button>

{{ money }}
<!--ROUND 2-->
<h1 STYLE="margin-left:10%; ">Problem Statements </h1>
<div class="fixed">
    <label
            style="background-color:black;color:#F3F3F3;font-family:serif;font-size:300%;margin-top:-15px;  "
    ><b>
        <span id="time1"></span></b>

    </label>
</div>
<table style="margin-left:3%; width:75%; height:70%;">
    <tr id="title" style=" font-weight: bold; font-size:145%;border:2px solid #E4E4E4;">
        <th>Question No</th>
        <th>DIFFICULTY</th>
        <th>SOLVE PROBLEM</th>
        <th>STATUS</th>
        <th>COST</th>
        <th>MARKS<th>
    </tr>
    {% for question in question_list %}

        <tr id="{{ forloop.counter }}">
        <td>{{ forloop.counter }}</td>
        <td>{{ question.difficulty }}</td>
        <td><a href="{% url 'round2:question_details' user_id question.question.pk %}"
               style=" font-size: 150%; text-align:left; margin-left:10%;">{{ question.question.question_title }}</a>
        </td>
        <td>{{ question.status }}</td>
        <td>{{ question.cost }}</td>
        <td>{{ question.question_score }}</td>
    {% endfor %}

    </tr>
</table>
</body>

<script type="text/javascript">

    function startTimer(duration, display) {
        var start = Date.now(),

            diff,
            minutes,
            seconds;

        function timer() {
            // get the number of seconds that have elapsed since
            // startTimer() was called
            diff = duration - (((Date.now() - start) / 1000) | 0);

            // does the same job as parseInt truncates the float
            hours = (diff / 3600) | 0;
            minutes = ((diff / 60) % 60) | 0;
            seconds = (diff % 60) | 0;
            hours = hours < 10 ? "0" + hours : hours;
            minutes = minutes < 10 ? "0" + minutes : minutes;
            seconds = seconds < 10 ? "0" + seconds : seconds;

            display.textContent = hours + ":" + minutes + ":" + seconds;


            if (diff <= 0) {
                // add one second so that the count down starts at the full duration
                // example 05:00 not 04:59
                // start = Date.now() + 1000;
                // window.location.replace("http:/comp/leaderboard/" );
                window.location.replace(" {%url 'round2:leaderboard' user_id %}");
            }

        };
        // we don't want to wait a full second before the timer starts
        timer();
        setInterval(timer, 1000);
    }

    window.onload = function () {
        var v = "{{remaining_time}}";

        display = document.querySelector('#time1');
        startTimer(v, display);
    };

</script>
</html>




round2/templates/round2/select_questions_new.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <title></title>
    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="{% static '/css/font.css' %}" rel="stylesheet">
    <script src="{% static '/js/jquery.min.js' %}"></script>
    <link rel="stylesheet"
          href="{% static '/css/jquery-ui.min.css' %}">
    <script src="{% static '/js/jquery-ui.min.js' %}"></script>

    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">


    <script src="{% static '/js/bootstrap.min.js' %}"></script>

    <style>
        .leader {
            background: whitesmoke;
        }
    </style>
</head>
<body>
<br>
<div class="container-fluid">
    <div class="container">
        <div class="row">
            <div class="col-md-2">

                <img alt="EarnCode"
                     src="{% static '/round2/images/ea.png' %}" width="100%">

            </div>
            <div class="col-md-4">
                <h2 style="margin-top: 60px;">CODE RELAY</h2>
            </div>
            
            <div class="col-md-2 col-md-offset-1 text-right">
                <div class="row"><h4 style="margin-top: 30px; margin-bottom: -5px; magin-right:10px">TIME</h4></div>
                <div class="row"><h2><span id="time1">time</span></h2></div>
            </div>

        </div>
    </div>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">

                    <li id="instruction_tab"><a onclick="showInstructions();">Instructions</a></li>
                    <li class="active" id="question_tab"><a onclick="showQuestions()">Question list</a></li>

                </ul>

                <form action="{% url 'round2:leaderboard' user_id %}" method="post" class="navbar-form navbar-right"
                      style="margin-bottom: -8px;margin-top: 1px;">
                    {% csrf_token %}
                    <!--<button type="submit" class="btn btn-default navbar-btn" id="leader" name="leader" value="test">View
                        Leaderboard
                    </button>-->
                    <button type="button" class="btn btn-default navbar-btn btn-danger" onclick="prompt_user()">
                        Finish
                    </button>

                </form>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>


    <div class="row">


    </div>

    <br>
    <div class="row leader" id="question_list">
        <div class="table-responsive">
                    <h1 style="font-size: 200%;">Problem Statement</h1>
                {% for question in question_list %}
                <a href="{% url 'round2:question_details' user_id question.question.pk %}"
                               style=" font-size: 150%; text-align:center; margin-left:10%;">{{ question.question.question_title }}</a>
                {% endfor %}
        </div>
    </div>

</div>
<div id="instruction" style="display: none;" class="container text-center">

    <div class="row">

        <div class="login-form col-md-6 col-md-offset-3">

            <ol>
                <p>
                <li> Second round consists of 4 problem statements which has 2 hours as the time limit.</li>
                <br>

                <li>This Round consists of 2 easy level questions, 2 medium level questions</li>
                <br>

                <li>Each easy level question is for 50 marks,Medium level question is for 100 marks
                </li>

                <br>
                <li>You are not suppose to press back and refresh buttons else you will be disqualified.</li>
                <br>


                </p>
            </ol>

        </div>
    </div>

</div>

<script>
        history.pushState(null, null, document.title);
        window.addEventListener('popstate', function () {
            history.pushState(null, null, document.title);
            alert('The only way is Ahead..!!!');
        });
    </script>

</body>

<script type="text/javascript">

    function startTimer(duration, display) {
        var start = Date.now(),

            diff,
            minutes,
            seconds;

        function timer() {
            // get the number of seconds that have elapsed since
            // startTimer() was called
            diff = duration - (((Date.now() - start) / 1000) | 0);

            // does the same job as parseInt truncates the float
            hours = (diff / 3600) | 0;
            minutes = ((diff / 60) % 60) | 0;
            seconds = (diff % 60) | 0;
            hours = hours < 10 ? "0" + hours : hours;
            minutes = minutes < 10 ? "0" + minutes : minutes;
            seconds = seconds < 10 ? "0" + seconds : seconds;

            display.textContent = hours + ":" + minutes + ":" + seconds;


            if (diff <= 0) {
                // add one second so that the count down starts at the full duration
                // example 05:00 not 04:59
                // start = Date.now() + 1000;
                // window.location.replace("http:/comp/leaderboard/" );
                window.location.replace(" {%url 'round2:instruction_view' user_id %}");
            }

        };
        // we don't want to wait a full second before the timer starts
        timer();
        setInterval(timer, 1000);
    }

    window.onload = function () {
        var v = "{{remaining_time}}";

        display = document.querySelector('#time1');
        startTimer(v, display);
    };

</script>
<script>
    function prompt_user() {
        if (confirm('Are you sure you want to save this thing into the database?')) {
            window.location.replace(" {%url 'round2:leaderboard' user_id %}");
        } else {
            // Do nothing!
        }
    }
</script>
<script>
    function showInstructions() {
        document.getElementById('question_list').style.display = "none";
        document.getElementById('question_tab').classList.remove('active');
        document.getElementById('instruction').style.display = "block";
        document.getElementById('instruction_tab').className += "active";

    }
</script>
<script>
    function showQuestions() {
        document.getElementById('instruction').style.display = "none";
        document.getElementById('instruction_tab').classList.remove('active');
        document.getElementById('question_list').style.display = "block";
        document.getElementById('question_tab').className += "active";

    }
</script>
</html>